#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  build_openwrt:
    name: Build OpenWrt firmware
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: 准备工作
        uses: actions/checkout@v2
      - name: 空间清理并部署编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
      - name: 下载源码
        run: git clone https://github.com/coolsnowwolf/lede openwrt
      - name: 写入插件到默认配置
        run: |
          cd openwrt
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
          echo "src-git package https://github.com/kjrzxu/package.git" >> ./feeds.conf.default
          echo "src-git openclash https://github.com/vernesong/OpenClash.git" >> ./feeds.conf.default
      - name: 编译5.10内核
        run: sed -i 's/PATCHVER:=5.4/PATCHVER:=5.10/' openwrt/target/linux/ramips/Makefile
      - name: 升级feeds
        run: cd openwrt && ./scripts/feeds update -a
      - name: 替换修改luci插件和配置
        run: chmod +x patch/diy-luci-add-rm.sh && sh patch/diy-luci-add-rm.sh
      - name: 修改luci插件名称和顺序
        run: chmod +x patch/diy-luci-order-name.sh && sh patch/diy-luci-order-name.sh
      - name: 安装feeds
        run: cd openwrt && ./scripts/feeds install -a
      - name: 配置config
        run: |
          cd openwrt
          cp ../.config .config
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: 下载软件包
        run: |
          cd openwrt
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h
      - name: 编译固件
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
      - name: 上传bin文件夹(固件+ipk)到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/
